// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbzxoaaexgyzunhkboqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhienhvYWFleGd5enVuaGtib3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzQ0NDUsImV4cCI6MjA3Mjg1MDQ0NX0.pc_4yEAo-9TeG4dCO8zsMNbSqUBGWnd5QhJQB04NfzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});